apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swimlane-app.fullname" . }}
  labels:
    {{- include "swimlane-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "swimlane-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "swimlane-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://{{ .Release.Name }}-mongo:27017/mydatabase